### ISSUE TITLE
Aircraft Checklist

### ISSUE THREAD

**Issue by arionkurtaj** [FGMEMBERS/MD-11#4]
Most aircraft have a aircraft checklist in flightgear however this aircraft doesn't have a aircraft checklist in flightgear. Would it be possible to add a aircraft checklist in flightgear telling you how to do a manual start of this aircraft. If somebody can reply to this it would be great.

**Comment by dg-505** [comment]
add them by yourself

**Comment by arionkurtaj** [comment]
I don't know them

**Comment by dg-505** [comment]
http://www.giyf.com

**Comment by FGDATA** [comment]
Besides, I don't know whether this aircraft has already been implemented
full operative manual start-up. That needs to be coded first, as well, and
it is, if needed, a larger overhaul and addition of systems.

[in other words, tipically is easier said that done! :( ]

Doable... but it is a large project.

@arionkurtaj. Jonathan tries to point out that we are a volunteer driven
project, and his message is just an invitation for you to help us ;)

**Comment by FGDATA** [comment]
@Jonathan,

I don't think there is any need to be rude here.

**Comment by IAHM-COL** [comment]
This is probably a more pertinent link for you @arionkurtaj

http://wiki.flightgear.org/Aircraft_Checklists

If you want to take a quick look at the fundamentals of adding checklist to
any aircraft.

I don't think Most aircraft in FG has these implemented. I would argue the
contrary to be true :)
But the more people learn how's done, the more planes will eventually have
it implemented (via volunteers submitting Pull Requests)

**Comment by arionkurtaj** [comment]
Ok I just need the checklist added to this aircraft

**Comment by ghost** [comment]
Uhh I can do it. I've flown a real MD-11 flightsim. Give me time though.

**Comment by jonathan** [comment]
@FGDATA could you please refrain from using @Jonathan. Since that's me and I have no idea what this project is and am not affiliated at all.

**Comment by arionkurtaj** [comment]
Ok thanks

**Comment by FGDATA** [comment]
@jonathan 
Sorry for the call in. My bad. :(

**Comment by arionkurtaj** [comment]
Ok
